name: instagram
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0
  badges: ^1.1.0
  page_transition: ^1.1.4
  url_launcher: ^5.1.4
  shimmer: ^1.0.1
  timeago: ^2.0.20
  email_validator: ^1.0.0
  font_awesome_flutter: ^8.5.0
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+6
  cloud_firestore: ^0.12.6
  firebase_auth: ^0.11.1+7
  connectivity: ^0.4.3+2
  firebase_storage: ^3.0.2
  google_sign_in: ^4.0.6
  flushbar: ^1.7.0
  intl: ^0.16.0
  flutter_advanced_networkimage: ^0.5.0
  simple_animations: ^1.3.3
  flutter_spinkit: ^4.0.0
  get_it: ^3.0.1
  image_picker: ^0.6.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

  